### ISSUE TITLE
Xcode 6.3 beta 2 (and beta 3) 

### ISSUE THREAD

**Issue by Alexanderrgonzales77** [nghialv/MaterialKit#17]
in the Classes 
MKimageView.swift
MKLayer.swift
MKTableViewCell.swift

The following lines of code appear 
-    override public func touchesBegan(touches: NSSet, withEvent event: UIEvent) {
       super.touchesBegan(touches, withEvent: event)
-        if let firstTouch = touches.anyObject() as? UITouch {

Which will need to be changed to the following in order to compile in the beta. 
+    override public func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent) {
        super.touchesBegan(touches, withEvent: event)
            +        if let firstTouch = touches.first as? UITouch {

I am merely advising this course of action and thought it would save you some time and trouble.

**Comment by Alexanderrgonzales77** [comment]
I should point out this only effects the beta builds listed above (with beta 3 being the current beta at the time i posted this)

**Comment by gali8** [comment]
replace it with:
```swift
    override func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent) {
        super.touchesBegan(touches as Set<NSObject>, withEvent: event)
        if let firstTouch = touches.first as? UITouch {
```

**Comment by evermeer** [comment]
Xcode 6.3 is now public and there are multiple build errors in MaterialKit
