### ISSUE TITLE
Error on buid

### ISSUE THREAD

**Issue by olivierto** [nghialv/MaterialKit#23]
Hey guys!
i'm getting this error on build time : 

MKTableViewCell.swift:54:48: Use of undeclared type 'Set'

```
override public func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent) {
```

I'm pretty new to swift, so any help would be much appreciated :+1:

**Comment by olivierto** [comment]
In fact it seems that it's a typo in method.
You should use : 
```
public override func touchesBegan(touches: NSSet, withEvent event: UIEvent) {
```

note i also need to change this in the method it self : 
```
if let firstTouch = touches.first as? UITouch {
```

to : 
```
super.touchesBegan(touches, withEvent: event)
        if let firstTouch = touches.allObjects[0] as? UITouch {
```

**Comment by nghialv** [comment]
Hi @olivierto . You should use Xcode6.3 to build this version.

**Comment by augustinepa** [comment]
I am getting nearly 17 errors while building my application with MaterialKit. I used cocoapods to add MaterialKit to my project. If I am manually adding the files (MaterialKit .swift files) to my project, then no error comes. Please let me know whether I missed something when using pods.
Thanks,
Augustine
