### ISSUE TITLE
Converting MKTextField to a string

### ISSUE THREAD

**Issue by craigpearce5** [nghialv/MaterialKit#33]
I'm still new to swift so this may be an easy answer.

Is there a way to convert an MKTextField into a string?  I'm using alamofire to create HTTP requests for login, however it doesn't support MKTextFields.

**Comment by powerje** [comment]
@craigpearce5 what code are you writing?

**Comment by craigpearce5** [comment]
@IBOutlet weak var login: MKTextField!
@IBOutlet weak var password: MKTextField!

Alamofire.request(Alamofire.Method.GET, "https://*******staging.herokuapp.com/operators/programs.json?email=\(login)&password=\(password)", parameters: nil, encoding: .JSON)

I've tried to first downcast as Strings by trying,

`let userMK = self.login as! String`

but it still doesn't work.

When I compile and run, this error is written to the console.
`fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) `

When I try to downcast, I get an xcode warning saying NSString is not a subtype of MKTextField.

**Comment by powerje** [comment]
what if you try using the text property on your `login` object?

i.e.:

`let username = self.login.text`

**Comment by craigpearce5** [comment]
Yes - that worked!!!

I never even thought of that.  Great idea.
