### ISSUE TITLE
Compilation errors with Swift 2.0

### ISSUE THREAD

**Issue by jpaas** [nghialv/MaterialKit#35]
I tried 0.3.5 out on a Swift 2.0/Xcode 7 project, but there are a number of compilation errors. Is Swift 2.0 support on the radar?

**Comment by evermeer** [comment]
until #32 is merged you could use:
pod 'MaterialKit', :git => 'https://github.com/mpclarkson/MaterialKit.git', :branch => 'swift2'

**Comment by nghialv** [comment]
Swift 2.0 support is now on the master.
