### ISSUE TITLE
Update Swift Syntax to 2.0

### ISSUE THREAD

**Issue by reesemclean** [nghialv/MaterialKit#40]
At the very least there needs to be a branch that we can point our podfiles at.

A pull request with the needed changes: https://github.com/nghialv/MaterialKit/pull/39.

Here is a branch others can use until this change is made: https://github.com/reesemclean/MaterialKit/tree/swift_2

    pod "MaterialKit", :git => "https://github.com/reesemclean/MaterialKit", :branch => "swift_2"

**Comment by PhilippeBoisney** [comment]
Thanks ! I just tested your code and it works like a charm :)

**Comment by TThana** [comment]
thanks

**Comment by fabioknoedt** [comment]
+1

**Comment by nghialv** [comment]
I have just merged your PR. Thank you so much. @reesemclean
