### ISSUE TITLE
Support for Swift 2.0 ?

### ISSUE THREAD

**Issue by rcholic** [nghialv/MaterialKit#45]
After I installed this MaterialKit using pod, it doesn't seem to support Swift 2.0. I was wondering if this is true or something is wrong with my settings. Thanks

**Comment by WasimMemon** [comment]
Heard anything from developer ?

**Comment by ishsingh** [comment]
@rcholic change your pod file like this:

pod 'MaterialKit', :head

**Comment by tengis** [comment]
@ishsingh thanks

**Comment by nghialv** [comment]
:+1:
