### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by grgcombs** [nghialv/MaterialKit#54]
Is MaterialKit dead/abandoned now?  Seems like there's not any owner activity with issues or pull requests in some time.

**Comment by craigpearce5** [comment]
+1

**Comment by zilions** [comment]
+1

**Comment by matryer** [comment]
+1

**Comment by i7clock** [comment]
+1

**Comment by eonist** [comment]
What about this: https://github.com/CosmicMind/Material

**Comment by grgcombs** [comment]
Holy macaroni.  That is amazing stuff right there.  I'm sold.

**Comment by craigpearce5** [comment]
I've used [CosmicMinds' Material](https://github.com/CosmicMind/Material) quite a bit in projects.  It's a great library and ever expanding.  The other great part is that the developers are very quick to answer questions or resolve issues.

**Comment by eonist** [comment]
Their support is best in class 100++ closed issues in a short amount of time. And they never leave you hanging for long it seems. By the way: The auther of this project officially stopped the project yesterday. Im not affiliated with cosmicmind. Just another stargazor :)
