### ISSUE TITLE
Error in swift 4

### ISSUE THREAD

**Issue by Rushabh5** [nghialv/MaterialKit#70]
Hi

I am trying to implement below screenshot scenario, but I am facing the issue so can you please help me in out.
![screen shot 2017-09-20 at 11 30 46 am](https://user-images.githubusercontent.com/16097116/30629070-7dab45ae-9df7-11e7-98f0-c5d07c692c70.png)

**Comment by shivamtiwari8736** [comment]
Hi @Rushabh5 ,
I am also stuck on the same errors.
Have you found any solution for the same?

Thanks.

**Comment by Rushabh5** [comment]
No @shivamtiwari8736 I have deleted this library in my project.

**Comment by shivamtiwari8736** [comment]
Oh! Actually I was updating code of an old project built 4 years before and this library is used in that. BTW Thanks for your quick response.
