### ISSUE TITLE
I can only get a square ripple

### ISSUE THREAD

**Issue by Huxpro** [nghialv/MaterialKit#8]
![image](https://cloud.githubusercontent.com/assets/5563315/5816021/8163d61e-a0d6-11e4-896c-9704ea1c3f6a.png)

I can not get a circle ripple in my project!
I just change the "custom class" to MKTableViewCell in the storyboard and it can only perform a square ripple. Same issues in TextField.

But if i copy one from your storyboard directly, it works.

**Comment by nghialv** [comment]
@Huxpro : please give me a link to download your code.

**Comment by Huxpro** [comment]
https://github.com/Huxpro/MKTest

Thankyou!

**Comment by nghialv** [comment]
@Huxpro Thank for your reporting. I have just updated my code. Please pull the new source.

**Comment by Huxpro** [comment]
Thx it works now!
