### ISSUE TITLE
 cocoapods support

### ISSUE THREAD

**Issue by thibault-fueled** [nghialv/MaterialKit#9]
Your library can't be used with cocapods, you need to make all those class public.

**Comment by dusterio** [comment]
I think it's still broken. Installation goes fine but there is a linking (build) issue whenever your pod is included

**Comment by rahuliyer95** [comment]
I followed [these](http://stackoverflow.com/questions/24002836/dyld-library-not-loaded-rpath-libswift-stdlib-core-dylib/26383255#26383255) steps and its working.

**Comment by MHaroonBaig** [comment]
@thibault-fueled @dusterio @rahuliyer95 One has to use the Beta version of the CocoaPods to make it work with the newer version of Xcode and Swift 1.2
I too struggled a lot, to make https://github.com/MHaroonBaig/MotionKit available through CocoaPods. Finally I ended up removing my existing installation and replace it with the Pre-released version of CocoaPods.
